plugins {
    id('scala')
    id('com.github.johnrengelman.shadow') version '8.1.1'
}

group = 'com.newsrx'
version = '0.1.0'

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/releases/' }
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.13.18'

    compileOnly 'io.github.gitbucket:gitbucket_2.13:4.46.0'
    compileOnly 'io.github.gitbucket:solidbase:1.1.0'
    compileOnly 'org.scalatra:scalatra-javax_2.13:3.1.2'
    compileOnly 'io.github.json4s:json4s-jackson_2.13:4.1.0'
    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    compileOnly 'com.github.takezoe:blocking-slick_2.13:0.0.14'

    testImplementation 'org.scalatest:scalatest_2.13:3.2.18'
    testImplementation 'org.scalatestplus:junit-4-13_2.13:3.2.18.0'
    testRuntimeOnly 'junit:junit:4.13.2'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    testCompileOnly 'io.github.gitbucket:gitbucket_2.13:4.46.0'
    testCompileOnly 'javax.servlet:javax.servlet-api:4.0.1'
    testRuntimeOnly 'io.github.gitbucket:gitbucket_2.13:4.46.0'
    testRuntimeOnly 'javax.servlet:javax.servlet-api:4.0.1'
    testRuntimeOnly 'com.github.takezoe:blocking-slick_2.13:0.0.14'
}

sourceSets {
    main {
        scala {
            srcDirs = ['src/main/scala', 'src/main/java']
        }
        java {
            srcDirs = []
        }
    }
}

test {
    useJUnit()
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
}

tasks.build.dependsOn shadowJar
